language: python
python:
  - '3.7'
dist: xenial
sudo: required

virtualenv:
  system_site_packages: true

install:
 - sudo apt-get update
 - sudo apt-get -y install python3-pyqt5
 - python setup.py install
